var test = "/////";
var peremeshat_voprosi = "да";
var vopros_1 = "1+1 =";
var vopros_2 = "2+2 =";
var vopros_3 = "3+3 = ";
var vopros_4 = "4+4 =";
var vopros_5 = "5+5 = ";
var vopros_6 = "6+6 = ";
var vopros_7 = "7+7 =";
var vopros_8 = "8+8 = ";
var vopros_9 = "9+9 = ";
var vopros_10 = "10+10 = ";
var vopros_11 = "11+11 = ";
var vopros_12 = "12+12 = ";
var vopros_13 = "13+13 = ";
var vopros_14 = "14+14 = ";
var vopros_15 = "15+15 =";
var vopros_ris_1 = "нет";
var vopros_ris_2 = "нет";
var vopros_ris_3 = "нет";
var vopros_ris_4 = "нет";
var vopros_ris_5 = "нет";
var vopros_ris_6 = "нет";
var vopros_ris_7 = "нет";
var vopros_ris_8 = "нет";
var vopros_ris_9 = "нет";
var vopros_ris_10 = "нет";
var vopros_ris_11 = "нет";
var vopros_ris_12 = "нет";
var vopros_ris_13 = "нет";
var vopros_ris_14 = "нет";
var vopros_ris_15 = "нет";
var pr_otv_zadachi_1 = "Mg=="; 
var pr_otv_zadachi_2 = "NA==";
var pr_otv_zadachi_3 = "Ng==";
var pr_otv_zadachi_4 = "OA==";
var pr_otv_zadachi_5 = "MTA=";
var pr_otv_zadachi_6 = "MTI=";
var pr_otv_zadachi_7 = "MTQ=";
var pr_otv_zadachi_8 = "MTY=";
var pr_otv_zadachi_9 = "MTg=";
var pr_otv_zadachi_10 = "MjA=";
var pr_otv_zadachi_11 = "MjI=";
var pr_otv_zadachi_12 = "MjQ=";
var pr_otv_zadachi_13 = "MjY=";
var pr_otv_zadachi_14 = "Mjg=";
var pr_otv_zadachi_15 = "MzA=";